### ISSUE TITLE
Invalid links for config.json file

### ISSUE THREAD

**Issue by kumarkrishna** [batra-mlp-lab/pcloudcv#19]
The file *config.json* is missing and referred to the following link :
 https://github.com/batra-mlp-lab/pcloudcv/blob/master/pcloudcv/config.json

The edits need to be made in the following :
* [README.md] (https://github.com/batra-mlp-lab/pcloudcv/blob/master/README.md "README.md")
* [Config Wiki](https://github.com/batra-mlp-lab/pcloudcv/wiki/Config-File)

Update the link with example file and the documentation for same.

**Comment by dexter1691** [comment]
@shubhamd already fixed it. Closing this
