### ISSUE TITLE
Broken link in README file

### ISSUE THREAD

**Issue by DESHRAJ** [batra-mlp-lab/pcloudcv#27]
The link of screenshot image(http://godel.ece.vt.edu/cloudcv/fileupload/media/pictures/output_new.gif) provided in README.md is showing 500 Internal server error.

**Comment by shubhamd** [comment]
Some of the files/functionalities have been moved to the new servers. These links will be fixed soon. #26  also has the same solution.

**Comment by DESHRAJ** [comment]
Ok. I just wanted to make sure that things are working fine. :)
